[build]
  publish = "frontend"
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://a44b4df8729c.ngrok-free.app.ngrok-free.app/api/:splat"
  status = 200
