[build]
  publish = "frontend"
  # This command creates frontend/config.js from the env var at build time
  command = "echo \"window.__CONFIG__={API_BASE_URL:'$API_BASE_URL'};\" > frontend/config.js"

[build.environment]
  NODE_VERSION = "18"
