[build]
  publish = "frontend"
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://7d207b6718e8.ngrok-free.app.ngrok-free.app/api/:splat"
  status = 200
